#MCE hub kubeconfig
hub:
  kubeconfig: kubeconfig-hub.yaml

#The cluster which will be imported
managed:
  kubeconfig: kubeconfig-managed.yaml

node:
  hostname: master3.compact.outbound.vz.bos2.lab
  role: master
  
  bmc:
    address: 192.168.58.15:8080
    username: Administrator
    password: dummy
    kvm_uuid: 22222222-1111-1111-0000-000000000003

  network:
    dhcp: false
    dns:
      - 192.168.58.15
      #- 2600:52:7:58::15
    interface: ens1f0
    mac: de:ad:be:ff:10:33
    ipv4:
      enabled: true
      ip: 192.168.58.33
      prefix: 25
      gateway: 192.168.58.1
    ipv6:
      enabled: false
      ip: 2600:52:7:58::33
      prefix: 64
      gateway: 2600:52:7:58::1


